spring.datasource.url=jdbc:postgresql://localhost:5433/beancounter
spring.datasource.username=postgres
spring.datasource.password=1234567

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=none

//JWT
jwt.secret=${JWT_SECRET:OZ0LHfKZvO94Mm7fW/BIluc4Fjz97xpyOFN+DYmEEYw=}
jwt.expiration=${JWT_EXPIRATION:86400000}